# Generated by Django 5.1.6 on 2025-05-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_executedcommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=100)),
                ('oper_status', models.CharField(max_length=20)),
                ('last_change', models.DateTimeField()),
                ('mac_address', models.CharField(max_length=17)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['name', '-timestamp'], name='login_inter_name_410d64_idx')],
            },
        ),
    ]
