# Generated by Django 5.1.6 on 2025-05-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_device'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='DeviceInfo',
        ),
    ]
