# Generated by Django 5.1.6 on 2025-05-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rename_device_deviceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.CharField(max_length=15)),
                ('metric_name', models.CharField(max_length=50)),
                ('metric_value', models.FloatField()),
                ('threshold_value', models.FloatField()),
                ('severity', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('memory', 'Memory Usage'), ('cpu_5s', 'CPU 5 Seconds'), ('cpu_1m', 'CPU 1 Minute'), ('cpu_5m', 'CPU 5 Minutes')], max_length=20)),
                ('threshold_value', models.FloatField()),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
