# Generated by Django 5.1.6 on 2025-06-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_interfacestatus_error_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='device_type',
            field=models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('pc', 'PC'), ('server', 'Server')], default='router', max_length=50),
        ),
    ]
