# Generated by Django 5.2.3 on 2025-06-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_deviceinfo_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDoSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('ddos_attack', 'DDoS Attack')], max_length=20)),
                ('source_ip', models.GenericIPAddressField()),
                ('target_ip', models.GenericIPAddressField()),
                ('detection_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved')], default='active', max_length=10)),
                ('severity', models.CharField(choices=[('critical', 'Critical')], max_length=10)),
                ('ai_confidence', models.FloatField(default=1.0)),
                ('blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('mitigation_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'DDoS Alert',
                'verbose_name_plural': 'DDoS Alerts',
                'ordering': ['-detection_time'],
            },
        ),
    ]
