# Generated by Django 5.1.6 on 2025-05-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=100)),
                ('total_memory', models.BigIntegerField()),
                ('used_memory', models.BigIntegerField()),
                ('free_memory', models.BigIntegerField()),
                ('lowest_usage', models.BigIntegerField()),
                ('highest_usage', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
