# Generated by Django 5.1.6 on 2025-05-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.GenericIPAddressField()),
                ('five_seconds', models.FloatField()),
                ('one_minute', models.FloatField()),
                ('five_minutes', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CPU Usage',
                'ordering': ['-timestamp'],
            },
        ),
    ]
