# Generated by Django 5.1.6 on 2025-05-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_interfacestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('uptime', models.CharField(max_length=100)),
                ('system_description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('device_ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
